// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRiV2MZcX0nt-MEtEdfIPcjmVlQ3CzEsI',
    appId: '1:493215236742:web:7738099671254bca80c707',
    messagingSenderId: '493215236742',
    projectId: 'myflutterapp2025-9db9f',
    authDomain: 'myflutterapp2025-9db9f.firebaseapp.com',
    storageBucket: 'myflutterapp2025-9db9f.firebasestorage.app',
    measurementId: 'G-GZNND56P2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4xq1emNzMgHOJKuDkabrUvw9Kj92hcE',
    appId: '1:493215236742:android:b8ec834544b68e0c80c707',
    messagingSenderId: '493215236742',
    projectId: 'myflutterapp2025-9db9f',
    storageBucket: 'myflutterapp2025-9db9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQv5hoW23G-SPOxUX5-fJeUdl0TWf3co',
    appId: '1:493215236742:ios:d2323804749b1bc080c707',
    messagingSenderId: '493215236742',
    projectId: 'myflutterapp2025-9db9f',
    storageBucket: 'myflutterapp2025-9db9f.firebasestorage.app',
    iosBundleId: 'com.example.project2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCQv5hoW23G-SPOxUX5-fJeUdl0TWf3co',
    appId: '1:493215236742:ios:d2323804749b1bc080c707',
    messagingSenderId: '493215236742',
    projectId: 'myflutterapp2025-9db9f',
    storageBucket: 'myflutterapp2025-9db9f.firebasestorage.app',
    iosBundleId: 'com.example.project2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRiV2MZcX0nt-MEtEdfIPcjmVlQ3CzEsI',
    appId: '1:493215236742:web:f876a777279412e380c707',
    messagingSenderId: '493215236742',
    projectId: 'myflutterapp2025-9db9f',
    authDomain: 'myflutterapp2025-9db9f.firebaseapp.com',
    storageBucket: 'myflutterapp2025-9db9f.firebasestorage.app',
    measurementId: 'G-RFJV15HQCK',
  );
}
