// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcX46vSZZvm3oQq1END4F1zwIBGMmBS3U',
    appId: '1:609329870561:web:38dec44e5d7b86bd1729a0',
    messagingSenderId: '609329870561',
    projectId: 'basictest-be3a7',
    authDomain: 'basictest-be3a7.firebaseapp.com',
    storageBucket: 'basictest-be3a7.firebasestorage.app',
    measurementId: 'G-1K03S2HM66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxr1VY-EPipoLc5v8KYjQF8TTIRy1Htco',
    appId: '1:609329870561:android:dc818d7955155e7c1729a0',
    messagingSenderId: '609329870561',
    projectId: 'basictest-be3a7',
    storageBucket: 'basictest-be3a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsU0Pl1WmgLIcWjnHqZul8le78va6bIY',
    appId: '1:609329870561:ios:4d6a239dddcc4ac91729a0',
    messagingSenderId: '609329870561',
    projectId: 'basictest-be3a7',
    storageBucket: 'basictest-be3a7.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsU0Pl1WmgLIcWjnHqZul8le78va6bIY',
    appId: '1:609329870561:ios:4d6a239dddcc4ac91729a0',
    messagingSenderId: '609329870561',
    projectId: 'basictest-be3a7',
    storageBucket: 'basictest-be3a7.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcX46vSZZvm3oQq1END4F1zwIBGMmBS3U',
    appId: '1:609329870561:web:42fdeef0a78feb891729a0',
    messagingSenderId: '609329870561',
    projectId: 'basictest-be3a7',
    authDomain: 'basictest-be3a7.firebaseapp.com',
    storageBucket: 'basictest-be3a7.firebasestorage.app',
    measurementId: 'G-FMHEZBKVL1',
  );
}
